### ISSUE TITLE
[question] checkbox values are lost after collapse

### ISSUE THREAD

**Issue by giuliohome** [JordanMarr/Fable.GroupingPanel#1]
In your example

```
select (
    tr [Key ("usr_" + user.Email)] [
        td [] []
        td[Style[LineHeight "30px"]] [
            str user.Email
        ]
        td [] [
            str user.Username
        ]
        td [] [
            input [
                Props.Type "checkbox"
                Style [Width "20px"; Height "32px"]
                Class B.``form-control`` 
                DefaultChecked (user.IsEnabled)
            ]
        ]
    ]
)
```

the value of the checkbox is lost without further implementation.

If you compare this with a [pure HTML+CSS summary/details](https://stackoverflow.com/a/15742338) strategy or a [simple javascript for the display](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_collapsible), the alternatives natively preserve the items.

Which is the strategy that you are assuming/suggesting to manage this issue? How/Why would the choice of react make things easier here?

**Comment by JordanMarr** [comment]
The Users example was meant to be a read-only list (that's why I used `DefaultChecked` instead of `Checked`), but I forgot to add  the `ReadOnly true` attribute.  It shouldn't allow you to change the check value as the checked state is not really editable.

Making this an editable list would involve storing the users list as component state, and then adding the `OnChange` event handler to the checkbox.


Are you implementing the GroupingPanel this using WebSharper React?

**Comment by JordanMarr** [comment]
Here is what an editable version would look like.
You can enable/disable users via the checkbox:

```
let page = React.functionComponent(fun () -> 
    let users, setUsers = React.useState([])

    React.useEffectOnce(fun () ->
        getFilteredUsers() |> setUsers
    )

    div [Class B.container] [
        div [Class B.row] [
            div [Class B.col] [
                table [classes [B.table; B.``mt-4``]] [
                    tbody [] [

                        let headerTemplate header = 
                            tr [Style [Background "#ececec"]; OnClick header.ToggleOnClick] [
                                td [ColSpan 4] [
                                    header.Chevron
                                    span [] [str (sprintf "%s (%i)" header.GroupKey header.Group.Length)]
                                ]                                    
                            ]

                        groupingPanel {
                            for user in users do
                            groupBy (if user.IsEnabled then "Active Users" else "Inactive Users")
                            groupHeader headerTemplate
                            groupCollapsedIf (not user.IsEnabled)
                            groupBy (getCompany user)
                            groupHeader headerTemplate
                            select (
                                tr [Key ("usr_" + user.Email)] [
                                    td [] []
                                    td[Style[LineHeight "30px"]] [
                                        str user.Email
                                    ]
                                    td [] [
                                        str user.Username
                                    ]
                                    td [] [
                                        input [
                                            Props.Type "checkbox"
                                            Style [Width "20px"; Height "32px"]
                                            Class B.``form-control`` 
                                            Checked (user.IsEnabled)
                                            OnChange (fun e -> 
                                                users |> List.map (fun u -> 
                                                    if u.Email = user.Email
                                                    then { u with IsEnabled = not u.IsEnabled }
                                                    else u
                                                ) |> setUsers
                                            )
                                        ]
                                    ]
                                ]
                            )
                        } 
                    ]
                ]
            ]
        ]
    ]
)
```

**Comment by giuliohome** [comment]
I was looking for a deeper motivation than a pure exercise of porting.
Thank you very much for answering with an editable version that makes the example even more interesting, from a business perspective.
Yeah, I think it makes sense for me to implement it in WebSharper React, since I often use WebSharper at work and I like it. Well, I honestly have some criticism against React, but I need to know it well, first of all.
So, thank you again for your prompt and complete replies, I will get back to you here as soon as I have news about my implementation and in the meantime we can certainly close my above question.

**Comment by giuliohome** [comment]
I've tried all this morning but I think that W# React is not sophisticated enough for this implementation, sorry.
Indeed I've never used W# React but always the react vars and views of W# (and I'm sure it can be easily implemented there without react)
Anyway I've posted my comments in [W# gitter channel](https://gitter.im/intellifactory/websharper?at=5f5df8c4b190f2328e6de7c0) by sharing an [online W# react snippet](https://try.websharper.com/snippet/user3383/0000Tv) that sadly doesn't work as expected

**Comment by giuliohome** [comment]
Any way I've fixed the macro issues.
You can find a rough porting (not styled) here in [this snippet online](https://try.websharper.com/snippet/user3383/0000Tv).
